#ifndef AND_RULE_H
#define AND_RULE_H

#include <Validation/Concepts/rule_concepts.h>
#include <Validation/Core/validation_result.h>
#include <Validation/Rules/rule_base.h>
#include <utility>

namespace validation {

  namespace rules {

    /**
     * @brief A composite rule that evaluates two rules sequentially.
     * The maximum capacity of this rule is the sum of the capacities of its
     * underlying left and right rules.
     * 
     * @tparam LeftRule The first rule to evaluate.
     * @tparam RightRule The second rule to evaluate.
     */
    template<HasCapacity LeftRule, HasCapacity RightRule>
    struct AndRule : RuleBase<LeftRule::capacity + RightRule::capacity> {
    private:
      /**
       * @brief Helper to merge the errors from an applied rule into the final result.
       * 
       * @tparam Rule The type of the applied rule.
       * @param finalResult The aggregated result accumulator.
       * @param appliedRuleResult The result generated by the individual rule.
       */
      template<HasCapacity Rule>
      constexpr void WriteAppliedRuleErrors(ValidationResult<AndRule::capacity>& finalResult,
        ValidationResult<Rule::capacity>& appliedRuleResult) const noexcept;

    public:
      /// The first rule to evaluate.
      LeftRule left_rule;

      /// The second rule to evaluate.
      RightRule right_rule;

      /**
       * @brief Constructs an AndRule by taking ownership of two rules.
       * 
       * @param leftRule The first rule.
       * @param rightRule The second rule.
       */
      constexpr explicit AndRule(LeftRule leftRule, RightRule rightRule)
        : left_rule(std::move(leftRule)), right_rule(std::move(rightRule)) {
      }

      /**
       * @brief Evaluates the value against both the left and right rules.
       * @tparam TVal The type of the value being validated.
       * @param value The value to validate.
       * @return A combined ValidationResult containing errors from both rules.
       */
      template<typename TVal>
        requires RuleFor<LeftRule, TVal>&& RuleFor<RightRule, TVal>
      constexpr auto operator()(const TVal& value) const noexcept;
    };

    template <HasCapacity LeftRule, HasCapacity RightRule>
    template <HasCapacity Rule>
    constexpr void AndRule<LeftRule, RightRule>::WriteAppliedRuleErrors(ValidationResult<AndRule::capacity>& finalResult,
      ValidationResult<Rule::capacity>& appliedRuleResult) const noexcept {
      for (std::size_t i = 0; i < appliedRuleResult.count; ++i) {
        finalResult.AddError(std::move(appliedRuleResult.errors[i]));
      }
    }

    template <HasCapacity LeftRule, HasCapacity RightRule>
    template <typename TVal>
      requires RuleFor<LeftRule, TVal>&& RuleFor<RightRule, TVal>
    constexpr auto AndRule<LeftRule, RightRule>::operator()(const TVal& value) const noexcept {
      auto left_result = left_rule(value);
      auto right_result = right_rule(value);

      ValidationResult<AndRule::capacity> final_result;

      WriteAppliedRuleErrors(final_result, left_result);

      WriteAppliedRuleErrors(final_result, right_result);

      return final_result;
    }
  } // namespace validation::rules

  /**
   * @brief Logical AND operator for combining validation rules.
   * * Allows chaining rules declaratively, e.g., `rule1 && rule2`.
   * * @tparam LeftRule The first rule.
   * @tparam RightRule The second rule.
   * @param leftRule The first rule instance.
   * @param rightRule The second rule instance.
   * @return A composed AndRule containing both rules.
   */
  template<HasCapacity LeftRule, HasCapacity RightRule>
  constexpr auto operator&&(LeftRule leftRule, RightRule rightRule) {
    return rules::AndRule<LeftRule, RightRule>{leftRule, rightRule};
  }

} // namespace validation

#endif // AND_RULE_H