#ifndef I_SERVER_ENCRYPTION_SERVICE_H
#define I_SERVER_ENCRYPTION_SERVICE_H

#include <string>

/**
 * @brief Interface for server-side cryptographic operations.
 *
 * Strictly limited to authentication (password hashing) and client identity
 * verification. Because the backend operates in a Zero-Knowledge architecture,
 * this interface intentionally lacks methods for data encryption/decryption.
 * 
 * Implementations should support Algorithm Agility (e.g., storing algorithm
 * identifiers within the resulting strings) to allow seamless cryptographic
 * upgrades in the future.
 */
class IServerEncryptionService {
public:
  virtual ~IServerEncryptionService() = default;

  /**
   * @brief Computes a secure cryptographic hash of a password.
   *
   * @param password The plaintext password to hash.
   * @return A self-contained string containing the algorithm identifier, salt, and hash.
   */
  virtual std::string HashPassword(const std::string& password) = 0;

  /**
   * @brief Verifies a plaintext password against a stored hash string.
   *
   * @param password The given plaintext password.
   * @param hash The stored composite string (containing algorithm, salt, and hash).
   * @return True if the password matches the hash, false otherwise.
   */
  virtual bool VerifyPassword(const std::string& password, const std::string& hash) = 0;

  /**
   * @brief Determines if a stored hash needs to be upgraded.
   *
   * This returns true if the stored hash uses an outdated algorithm,
   * or if the work factor/cost parameters have been increased since
   * the hash was originally generated.
   *
   * @param hash The stored composite string from the database.
   * @return True if the password should be re-hashed and updated.
   */
  virtual bool NeedsRehash(const std::string& hash) const = 0;

  /**
   * @brief Verifies a digital signature provided by a client.
   *
   * Used to prove identity (e.g., ensuring a client actually holds the private key
   * corresponding to their registered public key).
   *
   * @param data The plaintext data that was signed.
   * @param signature The encoded signature generated by the client.
   * @param publicKey The user's encoded public key.
   * @return True if the signature is authentic and valid, false otherwise.
   */
  virtual bool Verify(const std::string& data, const std::string& signature, const std::string& publicKey) = 0;
};

#endif // I_SERVER_ENCRYPTION_SERVICE_H