#ifndef I_SERVER_ENCRYPTION_SERVICE_H
#define I_SERVER_ENCRYPTION_SERVICE_H

#include <string>

/**
 * @brief Interface for server-side cryptographic operations.
 *
 * Strictly limited to authentication (password hashing) and client identity
 * verification. Because the backend operates in a Zero-Knowledge architecture,
 * this interface intentionally lacks methods for data encryption/decryption.
 */
class IServerEncryptionService {
public:
  virtual ~IServerEncryptionService() = default;

  /**
   * @brief Computes a secure cryptographic hash of a password.
   *
   * @param password The plaintext password to hash.
   * @return A string containing the salt and the resulting hash.
   */
  virtual std::string HashPassword(const std::string& password) = 0;

  /**
   * @brief Verifies a plaintext password against a stored hash.
   *
   * @param password The given plaintext password.
   * @param hash The stored hash/salt string from the database.
   * @return True if the password matches the hash, false otherwise.
   */
  virtual bool VerifyPassword(const std::string& password, const std::string& hash) = 0;

  /**
   * @brief Verifies a digital signature provided by a client.
   *
   * Used to prove identity (e.g., ensuring a client actually holds the private key
   * corresponding to their registered public key).
   *
   * @param data The plaintext data that was signed.
   * @param signature The Base64 signature generated by the client.
   * @param publicKey The user's stored public key in PEM format.
   * @return True if the signature is authentic and valid, false otherwise.
   */
  virtual bool Verify(const std::string& data, const std::string& signature, const std::string& publicKey) = 0;
};

#endif // I_SERVER_ENCRYPTION_SERVICE_H