#ifndef ROUTER_H
#define ROUTER_H

#include <functional>
#include <string>
#include <string_view>
#include <vector>

#include <boost/beast/http.hpp>
#include <boost/url.hpp>

namespace http = boost::beast::http;
namespace urls = boost::urls;

/**
 * @brief HTTP router.
 *
 * Maps incoming HTTP requests to specific controller handlers based on the HTTP verb
 * and the URI path.
 * 
 * It pre-computes route templates at startup to ensure the routing "hot path"
 * performs no dynamic memory allocations.
 */
class Router {
public:
  /**
   * @brief A container for extracted URI variables.
   */
  using PathParams = std::vector<std::pair<boost::core::string_view, boost::core::string_view>>;

  /// @brief The signature for controller methods handling matched routes.
  using HandlerFunc = std::function<http::response<http::string_body>(
    const http::request<http::string_body>&,
    const PathParams& params
  )>;

  /// @brief Represents a pre-compiled REST endpoint.
  struct Route {
    http::verb method;
    std::vector<std::string> segments;  ///< Static segments
    std::vector<std::string> param_names; ///< Names of dynamic segments
    std::vector<uint8_t> is_dynamic;  ///< Fast lookup flags for dynamic segments
    HandlerFunc handler;  ///< The controller callback
  };

  /**
   * @brief Registers a new REST endpoint.
   *
   * Pre-parses the path template (e.g., "/chats/{id}") into static and dynamic segments
   * at application startup, avoiding string parsing during live HTTP requests.
   *
   * @param method The HTTP verb (e.g., GET, POST).
   * @param pathTemplate The URI pattern, using {braces} for dynamic variables.
   * @param handler The controller function to execute upon a match.
   * @throws std::invalid_argument if the path template is a malformed URI.
   */
  void AddRoute(http::verb method, const std::string& pathTemplate, HandlerFunc handler);

  /**
   * @brief The routing hot-path. Matches an incoming request to a registered route.
   *
   * @param req The raw HTTP request from Boost.Beast.
   * @return The HTTP response generated by the matched handler, or a 404/400 error response.
   */
  http::response<http::string_body> RouteRequest(const http::request<http::string_body>& req);

private:

  /// @brief Checks if a template segment is a variable bounded by {braces}.
  static bool IsDynamicParameter(std::string_view segment);

  /// @brief Extracts the variable name and flags the segment as dynamic.
  static void ProcessDynamicParameter(Route& route, std::string_view param);

  /// @brief Registers an exact string match requirement for a segment.
  static void ProcessStringMatch(Route& route, std::string&& param);

  /// @brief Parses a complete URI template into the internal Route structure.
  void ProcessRouteTemplate(const boost::system::result<urls::url_view>& reqTemplateView, Route&& route);

  /**
   * @brief Attempts to match request segments against a route's template segments.
   *
   * Extracts dynamic variables into paramsOut if a match is found.
   * 
   * @return True if the URI matches the route, false otherwise.
   */
  static bool TryExtractParams(
    PathParams& paramsOut,
    const std::vector<uint8_t>& isDynamicIndicators,
    const std::vector<std::string>& paramNames,
    const urls::segments_view& requestSegments,
    const std::vector<std::string>& segments
  );

  /// @brief Iterates through registered routes to find a match and execute its handler.
  http::response<http::string_body> HandleRouting(const http::request<http::string_body>& req, const boost::system::result<urls::url_view>& reqTemplateView);

  /// @brief Generates a standard 404 Not Found response.
  static http::response<http::string_body> HandleNotFound(const http::request<http::string_body>& req);

  /// @brief Generates a standard 400 Bad Request response for malformed URIs.
  static http::response<http::string_body> HandleBadRequest(const http::request<http::string_body>& req);

  std::vector<Route> routes_;

  /// @brief Pre-allocation capacity to prevent heap allocations during parameter extraction.
  constexpr static std::size_t kAverageRouteParamCount = 5;

};


#endif // ROUTER_H